### ISSUE TITLE
Bug: Incorrect OBJ file processing

### ISSUE THREAD

**Issue by vsevolod-serbin** [acgessler/open3mod#108]
**Severity:** Major
**Environment:** Windows 10 x64

**Now:**
Application renders objects in OBJ file delivered via SketchUp Make in a strange and glitchy way.
Screenshots attached.
Original model in SketchUp:

![su-original](https://cloud.githubusercontent.com/assets/28601004/25955314/174b0004-3693-11e7-8bf0-655df5fe22aa.JPG)

Obj file in Open 3D model Viewer:

![m3d-obj](https://cloud.githubusercontent.com/assets/28601004/25955536/bec8d810-3693-11e7-88ef-bb933614026e.JPG)

**Steps to reproduce:**
1. Open obj [file](https://drive.google.com/open?id=0B7AdKqj0y4dTcnllbmZPdVc5bGc) (archive contains both files: obj and skp)

Also lights are glitching when zooming model: [video](https://drive.google.com/open?id=0B7AdKqj0y4dTdnNQTnlBeUU1R0k)

**Suggested:**
Investigate issues with sketchup compatibility.

**Comment by hhrhhr** [comment]
I personally do not see any errors and bugs from the viewer side. FBX Review shows exactly the same picture.
Problem in your file: there is no material library, so there are no textures; wrongly defined normals, so some objects look "inside out"; more precisely, in the original Sketchup model most of the faces are turned inside out.

**Comment by va-serbin** [comment]
Thanks for feedback on this. To be honest, I haven't checked the original model, that could be my fault. But I still see this as a minor issue. For instance, Microsoft 3d Viewer handled geometry in a more competitive way. 
I guess the same thing happened here: #112, I used this skp file in two cases.

And this is the picture from Microsoft 3d Viewer. Geometry and shadows are still messed up, but overall it looks better. 
![image](https://user-images.githubusercontent.com/28601004/27008806-dd99f6ae-4ea6-11e7-9577-2850f7ee6e2a.png)

**Comment by hhrhhr** [comment]
Again: in your model, almost all the normals are inverted to the model, for most 3D viewers this means an invisible face.

Open Sketchup, turn on monochrome and you'll see this:
![spo_wrong_normal](https://user-images.githubusercontent.com/966048/27009168-28999a4a-4e90-11e7-8317-fb684c6e4ecd.png)

And the correct model (after apply "Reverse faces" command) should look like this:
![spo_corrected normal](https://user-images.githubusercontent.com/966048/27009171-378580fa-4e90-11e7-8e37-810a3f0e65f2.png)

So there is no bug here, only the wrong original model.

**Comment by va-serbin** [comment]
Well, I'm totally agree, no bug here. My other point was that microsoft app had shown even broken model.
