### ISSUE TITLE
.NET Framework 4.5

### ISSUE THREAD

**Issue by MvGulik** [acgessler/open3mod#12]
Erm.
Finding out this 3D tool (open3mod) needs ".NET Framework 4.5" ... at installation ... is a major bummer.
As Win.Xp user this means a no go.
It would be nice to now in Advanced if something will run, or not, on your computer/OS.

Seriously dislike Dot.Net (Great MS tactic though)
Do like, and use, AssimpView (which by the looks of it is terminated. Bummer 2)

**Comment by acgessler** [comment]
I'll be updating the binaries in the next days. Current head is 3.5 only.
