### ISSUE TITLE
Building/running/closing app issue

### ISSUE THREAD

**Issue by gameengineer** [acgessler/open3mod#13]
If I use the pre-built binaries from the installer the open3mod.exe process closes but not when I build from source and load a model.  This is strange.  I am building the .NET 3.5 "Debug" and "Release" configurations.  Apart from a Devil copy error it builds and runs fine.

When I run the compiled version either Debug or Release and I do NOT open a model then the process closes fine.  But once I open model, even one of your Sample Scenes, the open3mod.exe process stays active when you close the app using the window red "x" button or File - Quit.  You can verify this in the Task Manager.  You can then launch multiple instances of open3mod.exe, all staying active if you load a model and then close.  Again your pre-built version does not do this.  I will continue to trace this but first I have to get familiar with C# again!  :)  I am a professional C++ developer and on occasion use C#.

Here is that error btw.
[quote]Error	2	The command "copy  C:\Dev\area51\Character\Open3D Viewer\open3mod-master\libs\devil-net\DevILNet\\..\Libs\x86\DevIL.dll ..\..\..\open3mod\bin\Release\
copy C:\Dev\area51\Character\Open3D Viewer\open3mod-master\libs\devil-net\DevILNet\\..\Libs\x86\ILU.dll ..\..\..\open3mod\bin\Release\" exited with code 1.	DevILNet
Warning	3	The field 'open3mod.FpsCameraController._rollAngle' is assigned but its value is never used	C:\Dev\area51\Character\Open3D Viewer\open3mod-master\open3mod\FpsCameraController.cs	45	23	open3mod
Warning	1	The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'c:\Dev\area51\Character\Open3D Viewer\open3mod-master\libs\Mono.Cecil\Net20\Mono.Cecil.dll'	C:\Dev\area51\Character\Open3D Viewer\open3mod-master\libs\assimp-net\AssimpNet.Interop.Generator\CSC	AssimpNet.Interop.Generator[/quote]

Running on Win7 x64 and compiling with Visual Studio 2013 w/Update 3.

-Steve

**Comment by dsewtz** [comment]
The current prebuilt standalone version v1.1 on windows 7 64bit has the same issue. 
Once you open an (.obj) file, the process continues to run after closing the window. It even keeps the file locked, so you can't move or delete it.

**Comment by acgessler** [comment]
Reproduced. This is critical so I'll try to get a fix out asap.

**Comment by acgessler** [comment]
Resolved by 1ec6ba1c1bb2afde569 but I still have to update the binaries.
