### ISSUE TITLE
major slowdowns

### ISSUE THREAD

**Issue by r-lyeh** [acgessler/open3mod#20]
hey there,

after a few hours running the client always becomes unresponssive and cpu hogging.
i guess either the timers did overflow or due to floating accumulation error inside the code (havent checked)

feasible reproduction steps (maybe) is to open the client, and advance the timers epoch a few days during runtime :s

anyways, great viewer : )
keep up the good work
- r-lyeh

**Comment by acgessler** [comment]
Thanks for reporting! I wasn't yet aware of this and I'll have a look.
