### ISSUE TITLE
AssimpNET lastest version

### ISSUE THREAD

**Issue by jdberwong** [acgessler/open3mod#21]
Hi Acgessler, am looking foward to the lastest version of assimpNet, but i found source files in google code, sourgeforce, github and i dont know what is the lastest. 

I want to make an aplication with the assimpNet Lib.

Hope you help me.

**Comment by acgessler** [comment]
I think google code is currently the one and only AssimpNet, so please take it from there.

https://code.google.com/p/assimp-net/

**Comment by jdberwong** [comment]
Thanks!
