### ISSUE TITLE
program instance stays resident (and hidden) after closing

### ISSUE THREAD

**Issue by r-lyeh** [acgessler/open3mod#30]
reproduction steps: open the viewer, load a model (tested w/ fbx & dae), and close the application. check that the application is still alive (but hidden from task bar) by using process explorer.exe from sysinternals (i pressume it will also show up in default taskmgr.exe but havent tested) 

it only happens on v1.1 i guess

**Comment by acgessler** [comment]
I believe I fixed an issue like this right after the 1.1 release and updated the binary (without bumping the version). Could you verify you have the latest binary?

**Comment by r-lyeh** [comment]
I downloaded it a few hours ago. Will try again tomorrow : )

**Comment by r-lyeh** [comment]
confirmed

**Comment by r-lyeh** [comment]
additional info: i believe the reproduction steps needs an animated mesh in either dae or fbx formats. for example, wuson mesh seems to exit properly.

**Comment by acgessler** [comment]
Thanks for nailing it down, I'll investigate over the weekend.
