### ISSUE TITLE
Window not visible

### ISSUE THREAD

**Issue by JLouis-B** [acgessler/open3mod#35]
Hi,
I have used Open3dMod during some weeks, it has worked well, thank for this great soft.
But since appromaximatly one week, I can't start the soft.
When I run it, the process appears in the process list of windows and in the task bar, but the window doesn't appears
When I put the mouse on the process in the taskbar, the miniature is correct like you can see on this picture, but impossible to have the window :
https://dl.dropboxusercontent.com/u/24460773/bug_open3dmod.png

I have tried to uninstall it and to reinstall it, I have still the same problem.
I don't know what can has caused this issue, I have do nothing special during the time where the soft works the beginning of the issue.

I use the version 1.1 from open3dmod.com on Windows 8.1 64 bits.

**Comment by r-lyeh** [comment]
have you ever used two monitors? may the window be outside the main screen?
focus the app, press alt-space, a popup will show, then choose move window, and use cursor keys until you see the window again :)

**Comment by JLouis-B** [comment]
I have never used two monitors.
I have made alt+space, a contextual menu has appeared at the top left corner of my screen, I have clicked "enlarge" and the window has appeared.
I don't know exactly what was the problem, but fixed now.

Thanks for the tip !

**Comment by r-lyeh** [comment]
:+1:

**Comment by acgessler** [comment]
To prevent this from happening in future, I added a check as to whether the saved location still maps to a screen.
